byte fram_homescreen()
{
	byte offset_l;
	byte offset_h;

	offset_h = 0;
	offset_l = 0;
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 1; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 2; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 3; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 4; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 5; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 6; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 7; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 8; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 9; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 10; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 11; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 12; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 13; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 14; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 15; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 16; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 17; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 18; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 19; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 20; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 21; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 22; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 23; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 24; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 25; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 26; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 27; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 28; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 29; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 30; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 31; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 32; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 33; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 34; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 35; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 36; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 37; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 38; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 39; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 40; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 41; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 42; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 43; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 44; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 45; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 46; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 47; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 48; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 49; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 50; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 51; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 52; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 53; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 54; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 55; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 56; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 57; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 58; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 59; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 60; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 61; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 62; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 63; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 64; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 65; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 66; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 67; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 68; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 69; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 70; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 71; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 72; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 73; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 74; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 75; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 76; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 77; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 78; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 79; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 80; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 81; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 82; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 83; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 84; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 85; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 86; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 87; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 88; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 89; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 90; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 91; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 92; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 93; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 94; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 95; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 96; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 97; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 98; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 99; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 100; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 101; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	

	offset_l = 0 + 102;
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 1 + 102;
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 2 + 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 3 + 102; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 4 + 102;
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 5 + 102;
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 6 + 102;
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 7 + 102;
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 8 + 102;
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 9 + 102;
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 10+ 102; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 11+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 12+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 13+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 14+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 15+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 16+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 17+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 18+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 19+ 102; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 20+ 102; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 21+ 102; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 22+ 102; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 23+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 24+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 25+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 26+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 27+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 28+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 29+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 30+ 102; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 31+ 102; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 32+ 102; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 33+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 34+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 35+ 102; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 36+ 102; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 37+ 102; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 38+ 102; 
	FRAM_write( 0xB, offset_h, offset_l ) ; 
	offset_l = 39+ 102; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 40+ 102; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 41+ 102; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 42+ 102; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 43+ 102; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 44+ 102; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 45+ 102; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 46+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 47+ 102; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 48+ 102; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 49+ 102; 
	FRAM_write( 0xD, offset_h, offset_l ) ; 
	offset_l = 50+ 102; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 51+ 102; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 52+ 102; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 53+ 102; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 54+ 102; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 55+ 102; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 56+ 102; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 57+ 102; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 58+ 102; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 59+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 60+ 102; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 61+ 102; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 62+ 102; 
	FRAM_write( 0x2, offset_h, offset_l ) ; 
	offset_l = 63+ 102; 
	FRAM_write( 0x2, offset_h, offset_l ) ; 
	offset_l = 64+ 102; 
	FRAM_write( 0x2, offset_h, offset_l ) ; 
	offset_l = 65+ 102; 
	FRAM_write( 0x2, offset_h, offset_l ) ; 
	offset_l = 66+ 102; 
	FRAM_write( 0x2, offset_h, offset_l ) ; 
	offset_l = 67+ 102; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 68+ 102; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 69+ 102; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 70+ 102; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 71+ 102; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 72+ 102; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 73+ 102; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 74+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 75+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 76+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 77+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 78+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 79+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 80+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 81+ 102; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 82+ 102; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 83+ 102; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 84+ 102; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 85+ 102; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 86+ 102; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 87+ 102; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 88+ 102; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 89+ 102; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 90+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 91+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 92+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 93+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 94+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 95+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 96+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 97+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 98+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 99+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 100+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 101+ 102; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	


	offset_l = 0  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 1  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 2  
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 3  
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 4  
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 5  
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 6  
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 7  
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 8  
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 9  
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 10; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 11; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 12; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 13; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 14; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 15; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 16; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 17; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 18; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 19; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 20; 
	FRAM_write( 0x2, offset_h, offset_l ) ; 
	offset_l = 21; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 22; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 23; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 24; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 25; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 26; 
	FRAM_write( 0x2, offset_h, offset_l ) ; 
	offset_l = 27; 
	FRAM_write( 0xB, offset_h, offset_l ) ; 
	offset_l = 28; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 29; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 30; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 31; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 32; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 33; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 34; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 35; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 36; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 37; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 38; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 39; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 40; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 41; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 42; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 43; 
	FRAM_write( 0x9, offset_h, offset_l ) ; 
	offset_l = 44; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 45; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 46; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 47; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 48; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 49; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 50; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 51; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 52; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 53; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 54; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 55; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 56; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 57; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 58; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 59; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 60; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 61; 
	FRAM_write( 0x9, offset_h, offset_l ) ; 
	offset_l = 62; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 63; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 64; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 65; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 66; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 67; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 68; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 69; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 70; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 71; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 72; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 73; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 74; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 75; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 76; 
	FRAM_write( 0x9, offset_h, offset_l ) ; 
	offset_l = 77; 
	FRAM_write( 0xD, offset_h, offset_l ) ; 
	offset_l = 78; 
	FRAM_write( 0xA, offset_h, offset_l ) ; 
	offset_l = 79; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 80; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 81; 
	FRAM_write( 0xD, offset_h, offset_l ) ; 
	offset_l = 82; 
	FRAM_write( 0x9, offset_h, offset_l ) ; 
	offset_l = 83; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 84; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 85; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 86; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 87; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 88; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 89; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 90; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 91; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 92; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 93; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 94; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 95; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 96; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 97; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 98; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 99; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 10); 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 10); 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	text_page + 4; 
	offset_l = 0  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 1  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 2  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 3  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 4  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 5  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 6  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 7  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 8  
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 9  
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 10; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 11; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 12; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 13; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 14; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 15; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 16; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 17; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 18; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 19; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 20; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 21; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 22; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 23; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 24; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 25; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 26; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 27; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 28; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 29; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 30; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 31; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 32; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 33; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 34; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 35; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 36; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 37; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 38; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 39; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 40; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 41; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 42; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 43; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 44; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 45; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 46; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 47; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 48; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 49; 
	FRAM_write( 0x9, offset_h, offset_l ) ; 
	offset_l = 50; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 51; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 52; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 53; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 54; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 55; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 56; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 57; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 58; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 59; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 60; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 61; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 62; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 63; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 64; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 65; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 66; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 67; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 68; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 69; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 70; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 71; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 72; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 73; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 74; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 75; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 76; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 77; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 78; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 79; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 80; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 81; 
	FRAM_write( 0xC, offset_h, offset_l ) ; 
	offset_l = 82; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 83; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 84; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 85; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 86; 
	FRAM_write( 0xD, offset_h, offset_l ) ; 
	offset_l = 87; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 88; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 89; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 90; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 91; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 92; 
	FRAM_write( 0x8, offset_h, offset_l ) ; 
	offset_l = 93; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 94; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 95; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 96; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 97; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 98; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 99; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 10); 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 10); 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	text_page + 5; 
	offset_l = 0  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 1  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 2  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 3  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 4  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 5  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 6  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 7  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 8  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 9  
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 10; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 11; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 12; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 13; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 14; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 15; 
	FRAM_write( 0xF, offset_h, offset_l ) ; 
	offset_l = 16; 
	FRAM_write( 0xE, offset_h, offset_l ) ; 
	offset_l = 17; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 18; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 19; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 20; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 21; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 22; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 23; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 24; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 25; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 26; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 27; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 28; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 29; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 30; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 31; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 32; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 33; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 34; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 35; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 36; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 37; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 38; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 39; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 40; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 41; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 42; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 43; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 44; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 45; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 46; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 47; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 48; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 49; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 50; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 51; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 52; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 53; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 54; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 55; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 56; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 57; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 58; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 59; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 60; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 61; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 62; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 63; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 64; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 65; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 66; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 67; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 68; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 69; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 70; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 71; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 72; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 73; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 74; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 75; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 76; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 77; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 78; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 79; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 80; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 81; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 82; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 83; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 84; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 85; 
	FRAM_write( 0x4, offset_h, offset_l ) ; 
	offset_l = 86; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 87; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 88; 
	FRAM_write( 0x2, offset_h, offset_l ) ; 
	offset_l = 89; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 90; 
	FRAM_write( 0x6, offset_h, offset_l ) ; 
	offset_l = 91; 
	FRAM_write( 0x7, offset_h, offset_l ) ; 
	offset_l = 92; 
	FRAM_write( 0x1, offset_h, offset_l ) ; 
	offset_l = 93; 
	FRAM_write( 0x3, offset_h, offset_l ) ; 
	offset_l = 94; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 95; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 96; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 97; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 98; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 99; 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 10); 
	FRAM_write( 0x0, offset_h, offset_l ) ; 
	offset_l = 10); 
	FRAM_write( 0x0, offset_h, offset_l ) ;

	return TRUE;
}